### ISSUE TITLE
Support for network: none in services

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#1001]
**Is your feature request related to a problem? Please describe.**
See [here](https://github.com/valory-xyz/open-autonomy/pull/1000#discussion_r904065241). Some services might not need a ledger at all, so it would be useful that we could specify network: none in the service yaml.

**Describe the solution you'd like**
Implement network optionality.

**Comment by DavidMinarsch** [comment]
Resolved with removal of network constants
