### ISSUE TITLE
wrong assertion in TestTendermintServerApp

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1011]
dropping this here because I am working on a Tendermint upgrade, but don't have a windows system at hand and it's a separate issue (as this commit bare the message:  "fix some more tests on windows").

@angrybayblade seems to be this commit: cda49e8

https://github.com/valory-xyz/open-autonomy/blob/2822968f858def392ebfd4d48906ce1a81548234/tests/test_deployments/test_app.py#L200-L208
would expect: `assert all(f.exists() for f in expected_file_names), expected_file_names`

P.S. nested `remove_prefix` function no longer needed

**Comment by DavidMinarsch** [comment]
This can be solved without Windows access.

**Comment by Karrenbelt** [comment]
addressing in #1012
