### ISSUE TITLE
Tendermint stops after a while when start_monitoring=False

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#1073]
### Subject of the issue
During ElCol QA we found that the default value (False) for `start_monitoring` in `abci/connection.py` makes the e2e tests fail. It looks like some buffer is filled and blocks it making Tendermint stop producing blocks. 

From Ardian:
`(Coming from google?) all PIPEs will deadlock when one of the PIPEs' buffer gets filled up and not read. e.g. stdout deadlock when stderr is filled. Never pass a PIPE you don't intend read`

We should write a test and then fix this.

### Your environment
- OS: Ubuntu 20.04
- Python version: 3.10
- Package Version: 0.1.2

### Steps to reproduce
Run a long e2e test with start_monitoring=False

### Expected behaviour
e2e test should run

### Actual behaviour
e2e fails

**Comment by marcofavorito** [comment]
This relates to a known problems with `subprocesses.Popen` when `stdout=PIPE` or `stderr=PIPE` is used:
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait

> Note: This will deadlock when using `stdout=PIPE` or `stderr=PIPE` and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use [`Popen.communicate()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) when using pipes to avoid that.

And indeed we use `wait` to wait for the process termination.

On the other hand, the Python documentation of `subprocess` gives another warning related to the use of `communicate()` (https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate):

> Note: The data read is buffered in memory, so do not use this method if the data size is large or unlimited. 

I guess we should be OK for our use case; still, good to have it in mind.
