### ISSUE TITLE
remove all references to USDT in oracle in case of USDT de-pegging.

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1114]
Presently, we use USDT should use either USDC or USDT everywhere

https://bitcoin.stackexchange.com/questions/95445/why-does-binance-use-usdt-instead-of-usd

yes suboptimal. So what happens when it loses its peg? It doesn't matter much for now though, but I dislike this because it's incorrect, rather would compare all to USDT or USDC then.

_Originally posted by @Karrenbelt in https://github.com/valory-xyz/open-autonomy/pull/1113#discussion_r928654741_

**Comment by DavidMinarsch** [comment]
This is a demo application. Agree with the point but also irrelevant given its a demo
