### ISSUE TITLE
Tendermint reset edge case

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#1126]
https://github.com/valory-xyz/open-autonomy/pull/1122#issuecomment-1197976368

**Comment by Adamantios** [comment]
Has not occurred again. Maybe we should close this issue.

**Comment by 0xArdi** [comment]
It occurred again [here](https://github.com/valory-xyz/open-autonomy/actions/runs/3539758889/attempts/1).

**Comment by Adamantios** [comment]
@0xArdi I believe that this is not relevant anymore since we are now syncing the agent's state during registration and recovery.

**Comment by 0xArdi** [comment]
@Adamantios agreed, we can close this.
