### ISSUE TITLE
Subgraph tests

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#1128]
### Subject of the issue
We have some tests in order to test the subgraphs' queries that we are using. However, these tests depend on a) network and b) an external resource, and therefore, they may occasionally fail. For example, test `tests/test_skills/test_apy_estimation_abci/test_apis.py::TestSubgraphs::test_top_n_pairs[UniswapSubgraph-uni_specs_pairs_extended]` fails in [main_workflow #4429](https://github.com/valory-xyz/open-autonomy/runs/7563825270?check_suite_focus=true).

There are 3 potential solutions:
1. The subgraphs cannot change once deployed, therefore we may skip the tests. That would be a problem if we updated a query incorrectly.
2. We may add a retry strategy to these tests.
3. We may mark all the tests that depend on network connectivity/external resources.

Solution (2.) might be the most appropriate at this point.

**Comment by DavidMinarsch** [comment]
I think we can add the retry for now
