### ISSUE TITLE
Skaffold file is incorrect

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1141]
### Subject of the issue

the skaffold file does not run.

The path is wrong for the open-aea Dockerfile

**Comment by 8ball030** [comment]
it should be 
![image](https://user-images.githubusercontent.com/35799987/181917339-64818da9-806a-4445-a321-5142445f2c12.png)

**Comment by 8ball030** [comment]
![image](https://user-images.githubusercontent.com/35799987/181917369-37d62b80-f684-44c9-af5c-c28b406e34b9.png)
Here is the error displayed on pulling the branch

**Comment by DavidMinarsch** [comment]
Yes I fixed that already :)

**Comment by DavidMinarsch** [comment]
Fixed https://github.com/valory-xyz/open-autonomy/pull/1139/commits/b145cf0492b181ff7e9b7495c3f3ef549a7e2165
