### ISSUE TITLE
[FEAT] -> Allow ropsten definition to used for test-deployments for infrastructure

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1156]
**Is your feature request related to a problem? Please describe.**
Presently when testing dev I have been using this profile for the past day;

oracle-cluster-ropsten

I would like to use this to test our deployments in staging. It is the closest we have to prod without being prod.

This will save me the time of generating a load of testnet keys and configurations / entirely remove the posibility of interactions between dev - Staging and prod.

Can you please set broadcast to server = false. on this file;
packages/valory/services/oracle_ropsten_cluster/service.yaml

**Comment by DavidMinarsch** [comment]
Already done
