### ISSUE TITLE
interdependency of skills and their tests

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1158]
There are tests for skill where we import classes from other skill while we should not. I have not systematically assessed the situation, but will list some of my findings here to illustrate.

https://github.com/valory-xyz/open-autonomy/blob/3ea8ff010d2b6ed55059ff43ee916a1371aff143/tests/test_skills/test_price_estimation_abci/test_rounds.py#L30-L33
https://github.com/valory-xyz/open-autonomy/blob/3ea8ff010d2b6ed55059ff43ee916a1371aff143/tests/test_skills/test_safe_deployment_abci/test_rounds.py#L26-L29
https://github.com/valory-xyz/open-autonomy/blob/3ea8ff010d2b6ed55059ff43ee916a1371aff143/tests/test_skills/test_transaction_settlement_abci/test_rounds.py#L37

the same thing goes for reuse of parts from tests. If not from `test_abstract_round.py` These should reside in some `base.py` or `helpers.py` script, e.g.
https://github.com/valory-xyz/open-autonomy/blob/3ea8ff010d2b6ed55059ff43ee916a1371aff143/tests/test_skills/test_safe_deployment_abci/test_rounds.py#L42-L48

Suggestion:

- test that concrete skills do not have any imports from other concrete skills
- a test for the same in the tests modules of concrete tests

**Comment by DavidMinarsch** [comment]
I agree on cleaning this up, but not on adding tests for tests. We can solve this conclusively by having tests co-located with code inside packages. Then the framework can take care of running tests for packages in isolation with a nice CLI entrypoint like `aea test PUBLIC_ID`
