### ISSUE TITLE
force `strict_check_strings` assignment on e2e tests

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1186]
I recommend turning a subset of the class attributes on `BaseTestEnd2End` into abstract methods - or force assignment some other way - in order to force overwrite at the concrete e2e test implementation.

right now if one does not overwrite the class attribute correctly, which has happened in the keep3r repository where [`check_strings`](https://github.com/valory-xyz/agent-academy-2/blob/1c07d0ab766a0c57d8239594fb7046ed78f3563e/tests/test_agents/test_keep3r_bot_abci.py#L43-L49) was provided instead of [`strict_check_strings`](https://github.com/valory-xyz/agent-academy-2/blob/1c07d0ab766a0c57d8239594fb7046ed78f3563e/tests/test_agents/base.py#L90), the tests actually do not test anything meaningful.

**Comment by 0xArdi** [comment]
Closed as it doesn't seem to be an issue for now, just the class attributes on the test have to be set right. Plus there are valid tests that don't need `strict_check_strings`.
