### ISSUE TITLE
Flaky counter_client tests in Windows

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#1190]
### Subject of the issue

[Two tests](https://github.com/valory-xyz/open-autonomy/runs/7805776380?check_suite_focus=true) are failing in Windows, but not in all python versions:
FAILED tests/test_skills/test_counter_client/test_behaviours.py::TestMonitorBehaviour::test_run
FAILED tests/test_skills/test_counter_client/test_behaviours.py::TestIncrementerBehaviour::test_run

**Comment by Adamantios** [comment]
Fixed on #1385.
