### ISSUE TITLE
Restrictions regarding class names in FSM spec

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-autonomy#1196]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
](https://github.com/valory-xyz/open-autonomy/pull/1192#discussion_r946559627)

**Describe the solution you'd like**
TBD, either add restrictions or have a smarter resolution

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1881
