### ISSUE TITLE
Add test to resolve file in scaffolder

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-autonomy#1197]
**Is your feature request related to a problem? Please describe.**
https://github.com/valory-xyz/open-autonomy/pull/1192#discussion_r946578912

**Describe the solution you'd like**
Do it

**Comment by DavidMinarsch** [comment]
Also, the scaffold tool should clean up if there is an error in the skill spec!

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1303
