### ISSUE TITLE
Remove the usage of staging chain

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-autonomy#1241]
Replace the usage of the staging chain with local node deployments

**Comment by DavidMinarsch** [comment]
At this point we only use it here: https://github.com/valory-xyz/open-autonomy/blob/main/autonomy/deploy/chain.py#L31
This can be replaced with the url for a local hardhat instance

**Comment by DavidMinarsch** [comment]
Also of the staging server: https://github.com/valory-xyz/open-autonomy/blob/704dfb5ec0b10f560e12d9f2806df2cae15c3ba7/autonomy/deploy/chain.py#L30

We should instead store the abis locally as we don't want them to be dynamically changed anyway.
