### ISSUE TITLE
`DictProtobufStructSerializer` support for list, tuple, set, frozenset

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1258]
we do not support encoding of lists, tuples and sets in our [`DictProtobufStructSerializer`](https://github.com/valory-xyz/open-autonomy/blob/main/packages/valory/skills/abstract_round_abci/serializer.py). A current work-around is the use of `dict(zip(container, container))` as far as the protobuf serializer is concerned, but it has the downside of creating a non-hashable object in case you were using a tuple or frozenset.

The use case of which affects any payload returning such a key as part of their data

**Comment by Karrenbelt** [comment]
lets also add support for deque while at it, we use it in here
https://github.com/valory-xyz/open-autonomy/blob/60885be17c309ff660bbc0929e8c0ad6a3f6adb0/packages/valory/skills/transaction_settlement_abci/rounds.py#L110-L119

on a side note: Idea for refactoring will need to be explored, but it appears to me we can design things in a way that transaction type can correspond one-to-one with what is stored in the shared state. Furthermore I am of the opinion we should constrain more. E.g. no computation on synchronized data object, that is not its purpose. To illustrate: the transaction type can directly be used to determine the content that will end up in the synced database, you don't get to pick another random name yourself. `SELECT_KEEPER = "select_keeper_tranaction` will just be `selected_keeper`.

**Comment by DavidMinarsch** [comment]
The last point has pros and cons. The synchronized data object should never be altered from other than rounds (not trivial to implement outside conventions!) but I don't think we need to entirely prevent custom methods on it. The dev can decide.
