### ISSUE TITLE
`BaseTxPayload`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1259]
Current implementation of [BaseTxPayload](https://github.com/valory-xyz/open-autonomy/blob/c2e66f30e9a14d0395827014952b58280f1407ab/packages/valory/skills/abstract_round_abci/base.py#L181)

1. the `.data` property returns an empty dict by default, which is undesirable as a developer may neglect to do so. An `abstractmethod` is preferred to ensure the developer overwrites. Some example [here](https://github.com/valory-xyz/agent-academy-2/pull/90/files/a8dc04549e3fd0fc7d3dd860f0587f4c09a72ebc#diff-ba07b9d43cd411d1df889627ff8ad7d067e9d47cffef4a39f3b5c83dcb5a3d88R52-R58)
2. it can be abstracted away entirely, including the need to implement properties. See this [trello ticket](https://trello.com/c/vUXhoF4x/394-refactor-implement-payload-class-redesign). There therein proposed design simplifies the implementation of concrete rounds to:

```
class PayloadA(BaseTxPayload):

    __slots__ = ["a", "b"]
    transaction_type = TransactionType.TEST

    def __init__(self, sender, id_, a, b):
        super().__init__(sender, id_, a, b=b)
```

## NOTES
The `__hash__` overwrite is problematic as noted in #1003. If we freeze the class upon instantiation then this is less of an, or perhaps no longer, an issue. The design in the Trello ticket is suboptimal as well; it's too simplistic (no regard for ordering, no nested structures). 
We should clarify the need and current use of this method first before re-implementing. Should only `.data` be hashed such that instance A and B are equal regardless of their `_id`, `sender` and `round_count`? If yes, then lets reuse the serializer we are already using perhaps. Maybe support other containers than dict as well [#1258](https://github.com/valory-xyz/open-autonomy/issues/1258) 

Note that we cannot do this because of mutable attributes.
```
    def __hash__(self) -> int:
        """Hash the payload."""
        return hash(str(self.json))
``` 

we may consider:
```
    def __hash__(self) -> int:
        """Hash the payload."""
        return hash(DictProtobufStructSerializer.encode(payload.data))
```

**Comment by DavidMinarsch** [comment]
Recent refactors addressed this
