### ISSUE TITLE
FSMBehaviourBaseCase.setup

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1263]
We should convert existing `setup` from setup to `setup_class` and then here you can write a custom setup run before each test method is called. Be mindful that this change will affect child classes, also of those using this in other repositories. 

https://github.com/valory-xyz/open-autonomy/blob/5c32acfaec3bb5e0d9bc79426436f97002b5918c/packages/valory/skills/abstract_round_abci/test_tools/base.py#L79-L80

**Comment by DavidMinarsch** [comment]
Not all code in `setup` can be moved to the class level. This is probably safe to move https://github.com/valory-xyz/open-autonomy/blob/main/packages/valory/skills/abstract_round_abci/test_tools/base.py#L91-L116 and this too https://github.com/valory-xyz/open-autonomy/blob/main/packages/valory/skills/abstract_round_abci/test_tools/base.py#L122-L123. Also we call `super.setup()` so it's important to understand what's done in the base class in setup before simply moving it to class wide setup
