### ISSUE TITLE
Copyright notice header `autonomy scaffold` incorrect

### ISSUE THREAD

**Issue by 0xArdi** [valory-xyz/open-autonomy#1281]
The copyright notice header for auto-generated files via `autonomy scaffold fsm` produces incorrect output.
Ex:
```
#   Copyright 2021 Valory AG
#   Copyright 2018-2019 Fetch.AI Limited
```
This is from an autogenerated file generated on 2022/09/05. 
The year for Valory is 2021, I think it should be 2022, as in some of the other autogenerated files it was 2022.
Furthermore, I think only Valory should be listed as a copyright holder.

**Comment by DavidMinarsch** [comment]
I would go further and say we should make it: `f"Copyright {year} {author}"`

**Comment by Karrenbelt** [comment]
I only find these after scaffolding, low priority:
```
./__init__.py:#   Copyright 2018-2019 Fetch.AI Limited
./my_model.py:#   Copyright 2018-2020 Fetch.AI Limited
```
