### ISSUE TITLE
Scaffolding TODO's

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1289]
This ticket exists to collect items regarding the FSM scaffolding.

- ~~'author' should be configurable~~
  ~~author keyword in `RoundTestsFileGenerator`, `BehaviourTestsFileGenerator`~~
- ~~link to relevant documentation in base classes of rounds, behaviour, etc. and their tests where useful~~ decided against
- ~~scaffold payloads~~ #1291 
- ~~scaffold dialogues~~ #1290 
- ~~test to see if scaffolded packages can be "run" (to ensure imports are correct and working)~~ #1303 
- ~~remove `--skip-consistency-check` in `TestScaffoldFSM`~~ 
- `Base{FSMName}Payload(BaseTxPayload)` [reference](https://github.com/valory-xyz/open-autonomy/pull/1291#discussion_r964026974)
- ~~constants for "Behaviour" and "Round" strings.~~ [reference](https://github.com/valory-xyz/open-autonomy/pull/1303) #1310
- ~~Check and fix docs strings~~ #1310

**Comment by DavidMinarsch** [comment]
"link to relevant documentation in base classes of rounds, behaviour, etc. and their tests where useful" would be useful but will end up outdated asap. Let's not do it.

**Comment by DavidMinarsch** [comment]
Also this: https://github.com/valory-xyz/open-autonomy/issues/1281

**Comment by DavidMinarsch** [comment]
'author' should be configurable -> what do you mean by this? The author should be taken from cli config.

**Comment by Karrenbelt** [comment]
> 'author' should be configurable -> what do you mean by this? The author should be taken from cli config.

yes it is now. I noticed I only crossed out the second line not the first; edited.
