### ISSUE TITLE
Update `publish` command to take care of temporary files while publishing service package.

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-autonomy#1315]
Right now we upload the service folder as it is. Since we have introduced the new deployment flow we might wanna change that since now it can contain temporary files like build directories and key files

**Comment by DavidMinarsch** [comment]
This could be achieved by interpreting `fingerprint_ignore_patterns` also as ignore patterns for when the outer hash is created. This means, when they are set, we'd have to create a temp dir which does not contain all the to-be-ignored files and folders, hash that and push to IPFS.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1889
