### ISSUE TITLE
--dev flag in kubernetes deployment populates with incorrect host.

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1337]
### Subject of the issue

1. when deploying in dev mode in the cluster, we set the ledger address host to 
```
http://host.docker.internal:8545
```

It should be
```
http://hardhat:8545
```
Other than this, everything works as expected.

### Steps to reproduce
```
autonomy fetch valory/oracle_hardhat --local --service
cd oracle_hardhat
autonomy build-image
autonomy deploy build  ../generated_keys.json --force --password ${PASSWORD} --kubernetes --dev
kubectl apply -f abci_build/
kubectl apply -f abci_build/agent_keys
```
within the build.yaml, if you look at the LEDGER address you will notice that it is set to the host for the docker-compose deployment

### Actual behaviour
Tell us what happens instead

**Comment by DavidMinarsch** [comment]
Ok, this is an issue with the configuration of the service. I think we can close this issue once the docs are updated. A user wanting to run this service with kubernetes has the extra step of replacing the override in the `service.yaml`

**Comment by 8ball030** [comment]
Perfect
