### ISSUE TITLE
Add `callback` argument to relevant `BaseState` methods

### ISSUE THREAD

**Issue by marcofavorito** [valory-xyz/open-autonomy#134]
**Is your feature request related to a problem? Please describe.**
It is currently not straightforward to change the default behaviour of the `BaseState` methods that send requests to third-party services. In particular, the callback is hard-coded to be the `default_callback_request`.

**Describe the solution you'd like**
Add `callback` argument to relevant `BaseState` methods, which defaults to `default_callback_request`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Closed on recommendation of @0xArdi . "The callback mechanism for handling messages is not the same state as it was when this ticket was created. We've had to add custom callbacks multiple times, and I don't think its that tricky, ex. [open-autonomy/behaviours.py at main · valory-xyz/open-autonomy](https://github.com/valory-xyz/open-autonomy/blob/main/packages/valory/skills/termination_abci/behaviours.py#L489)"
