### ISSUE TITLE
THIRD_PARTY_CONTRACTS

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1342]
It seems third party module default is wrongly specified. `PACKAGE_DIR` should be `ROOT_DIR` in 
`os.environ.get("THIRD_PARTY_CONTRACTS", PACKAGE_DIR / "third_party") `

contracts:
https://github.com/valory-xyz/open-autonomy/blob/66b9f50bd315860e6579a6e9268eaa69a26881be/packages/valory/contracts/gnosis_safe_proxy_factory/tests/test_contract.py#L35-L38
https://github.com/valory-xyz/open-autonomy/blob/66b9f50bd315860e6579a6e9268eaa69a26881be/packages/valory/contracts/gnosis_safe/tests/test_contract.py#L61-L64
https://github.com/valory-xyz/open-autonomy/blob/66b9f50bd315860e6579a6e9268eaa69a26881be/packages/valory/contracts/uniswap_v2_router_02/tests/test_contract.py#L36-L39
https://github.com/valory-xyz/open-autonomy/blob/66b9f50bd315860e6579a6e9268eaa69a26881be/packages/valory/contracts/offchain_aggregator/tests/test_contract.py#L40-L43

integration:
https://github.com/valory-xyz/open-autonomy/blob/66b9f50bd315860e6579a6e9268eaa69a26881be/packages/valory/skills/oracle_abci/tests/test_integration.py#L91-L94
https://github.com/valory-xyz/open-autonomy/blob/66b9f50bd315860e6579a6e9268eaa69a26881be/packages/valory/skills/liquidity_provision_abci/tests/test_integration.py#L86-L89

**Comment by DavidMinarsch** [comment]
This was intentional. Is also irrelevant now #1339
