### ISSUE TITLE
Behaviour : Round : Payload references

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1356]
**Is your feature request related to a problem? Please describe.**

1. There should be no need for a developer to specify a `behaviour_id`, `round_id`. 
These can simply be derived from the name of the class, at least as a default, and then overwritten in case necessary. Adding them as properties won't work though, since the meta class checks them, however this can easily be replaced by the metaclass checking the class name is unique instead.

2. the round should specify `payload` instead of `allowed_tx_type`. 
It should reference the `payload` itself instead, and the `transaction_type` can be accessed via it. This is much more intuitive, less redundant and hence less error prone and easier to scaffold as a bonus. The result would be that a behaviour references its corresponding round (`matching_round`) and that round references its corresponding payload.

3. The `payload_attribute` should be removed from rounds.
This references the name of the attribute / key of the content of the payload. It is superfluous since it can be replaced entirely by the `Payload.transaction_type`. This relates to issue #371

The result would be a single class attribute on Behaviour, namely `round` (now: `matching_round`), a single class attribute on the Round, namely the `payload`, and a single class attribute on the Payload, the `transaction_type`.

Behaviour -> Round -> Payload -> TransactionType: `behaviour.round.payload.transaction_type`

Since the relationships are 1 : 1 : 1, we can also make payload accessible directly on the behaviour, which is where we need to create it, further simplifying the implementation for the developer. 
https://github.com/valory-xyz/open-autonomy/blob/09f514b9d4ffb92fc8a6ae755ee94450358cb540/autonomy/cli/scaffold_fsm_templates/components.py#L165-L168
The scaffolded class may looks as follows:

```
    def async_act(self) -> Generator:
        \"\"\"Do the act, supporting asynchronous execution.\"\"\"

        with self.context.benchmark_tool.measure(self.behaviour_id).local():
            # TODO: set content based on some criterion (e.g. synchronized_data)
            content = ...
            sender = self.context.agent_address
            payload = self.create_payload(sender, content)
    
        with self.context.benchmark_tool.measure(self.behaviour_id).consensus():
            yield from self.send_a2a_transaction(payload)
            yield from self.wait_until_round_end()
    
        self.set_done()
```

**Comment by DavidMinarsch** [comment]
Recent changes in payload design address all these
