### ISSUE TITLE
Address `.hypothesis` residues

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#1374]
Address `.hypothesis` residues.

_Originally posted by @Adamantios in https://github.com/valory-xyz/open-autonomy/pull/1373#discussion_r977435312_

We need to run this before generators (which btw has `rm -fr .hypothesis`  duplicated):
https://github.com/valory-xyz/open-autonomy/blob/f6fdb544e20b8d6e72da1518fccf15ec983f8695/Makefile#L34-L46

**Comment by DavidMinarsch** [comment]
I think running the whole clean would be inefficient as you loose the cached info from `.tox/` etc. I suggest splitting `clean-test` and then just running the cleaner for the files which can appear inside packages.

Although, most ideally there is no residues. With pytest it can all be run in memory afaik (cc @angrybayblade )
