### ISSUE TITLE
E2e tests pass when they should not

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1407]
### Subject of the issue

Running the registration startup e2e tests with both public nodes leads to (expected) failures of the test, whereas using only one of the two, no matter which, the tests pass. Closer inspection of the logs on these single node runs, however, showed that no connection whatsoever was made to the public ACN, and what's more, that the `happy_path` and `strict_check_strings` messages were not present in the logs either.

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by Karrenbelt** [comment]
It turns out there is no failure and the tests work as expected. It simply appears the agent messages are no longer printed to stdout, leading me to believe that the logging configuration has changed. That is to say, adding a check for a log or round that does not exist will lead to the expected test failure. I am used to checking logs from e2e test that I pipe to a file using grep, but this doesn't work anymore. I will close this issue once understanding what configuration changed and why.

**Comment by Adamantios** [comment]
Closing as this is not an issue.
