### ISSUE TITLE
Create release images

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#1442]
After extracting the [APY](https://github.com/valory-xyz/apy) and the [price-oracle](https://github.com/valory-xyz/price-oracle.git), we do not have access to the `autonomy/data`, which means that we do not have access to the `Dockerfiles`. Therefore, we cannot use the agents `Dockerfile` in order to generate the release images, except if we duplicate it there.

Should we add a CLI command for that?

**Comment by DavidMinarsch** [comment]
We don't need access to that folder. The images will already be pushed

**Comment by Adamantios** [comment]
I am referring to [this](https://github.com/valory-xyz/open-autonomy/blob/9e446963182c459d27e843350df552e7eccf4fcb/autonomy/data/Dockerfiles/agent/Dockerfile) file. I am probably missing something, I cannot see how this is not necessary.

**Comment by 0xArdi** [comment]
The [agent Dockerfile](https://github.com/valory-xyz/open-autonomy/blob/v0.3.2/autonomy/data/Dockerfiles/agent/Dockerfile) takes the agent as a build-time dependency. We can just have a cli command in `autonomy` to provide the correct build time argumnets/environment variables, and we could reuse the same. 
Multi-stage builds doesn't make much sense here, we need to use the same Dockerfile, not add any extra functionalities to it.

Another way to do it would be to have the Dockerfile install the agent at runtime. This would mean that we would push a base image to dockerhub, and anybody wanting to run their agent would provide the necessary information via arguments/environment variables. But that would mean that the agent would be installed at every run, which we don't think it's ideal.

**Comment by angrybayblade** [comment]
We already have a command in autonomy cli to handle such cases. `autonomy build-image` can take a public id for an agent to build and tag the image. https://docs.autonolas.network/autonomy/#build-tools 

Only problem with the CLI tool is it does not support for custom tags, the tags are autogenerated from the agent's public ID in following format 

`valory/oar-{agent_name}:{agent_hash}`

**Comment by Adamantios** [comment]
Thanks! We can close this issue.

What misled me was the `--help` description of the command:

```
Usage: autonomy build-image [OPTIONS] [PUBLIC_ID_OR_HASH]

  Build image using skaffold.

Options:
  --service-dir PATH  Path to service dir.
  --dev               Build developement image.
  --pull              Pull latest dependencies.
  --help              Show this message and exit.
```

 We should add a help description for the agent argument too.
