### ISSUE TITLE
Flaky test: `TestCheckSpecs`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1465]
CI runs:
- https://github.com/valory-xyz/open-autonomy/actions/runs/3299364388/jobs/5442762734
- https://github.com/valory-xyz/open-autonomy/actions/runs/3299364388/jobs/5442762910
- and more in #1464

```
FAILED tests/test_autonomy/test_cli/test_analyse/test_abci/test_specs.py::TestCheckSpecs::test_check_all_fail
FAILED tests/test_autonomy/test_cli/test_analyse/test_abci/test_specs.py::TestCheckSpecs::test_check_all
```

[failure.log](https://github.com/valory-xyz/open-autonomy/files/9842099/failure.log)

**Comment by angrybayblade** [comment]
Fixed here https://github.com/valory-xyz/open-autonomy/pull/1457
