### ISSUE TITLE
Refactor the `valory/gnosis_safe` tests

### ISSUE THREAD

**Issue by 0xArdi** [valory-xyz/open-autonomy#1473]
There is a lot of duplication in the [gnosis safe tests](https://github.com/valory-xyz/open-autonomy/blob/v0.3.3/packages/valory/contracts/gnosis_safe/tests/test_contract.py) tests, as pointed out [here](https://github.com/valory-xyz/open-autonomy/pull/1469).

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1533
