### ISSUE TITLE
Feat/Custom Host Os Install Scripts

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1489]
**Is your feature request related to a problem? Please describe.**
When attempting to build services with complex dependencies which require host level installs, 
it is impossible to get these installed on the docker images.
This means, that you cannot run a dockerized agent.

**Describe the solution you'd like**
A) a specification within the service spec which defines any host level dependencies.
Ansible does this really well; (This is a python lib as well)
![image](https://user-images.githubusercontent.com/35799987/198995602-174bceb5-99be-4fe1-8d61-dbad79c8778d.png)

This ansible spec could be included within the spervice spec and then could be used within the docker-images as a last-leg step to prepare them for custom libs.

**Comment by DavidMinarsch** [comment]
Interesting idea. Consider also in this context the existing functionality here: https://github.com/valory-xyz/open-aea/blob/main/aea/configurations/base.py#L221

**Comment by 8ball030** [comment]
https://github.com/valory-xyz/open-autonomy/blob/20551f16131c8de0144729f2422bcca91e2210b6/autonomy/data/Dockerfiles/agent/install.sh#L16

This would very simple to implement.

I believe adding 
```
aea build 
```
in line 15

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1954
