### ISSUE TITLE
Replace with new storage class

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1508]
https://github.com/valory-xyz/open-autonomy/blob/a96dbcff77f19b545db185ac1e1bc4c864e30003/autonomy/deploy/generators/kubernetes/templates.py#L119

nfs-client should be replaced with;

```
nfs-ephemeral
```

for all occurances

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1524
