### ISSUE TITLE
Generate Agent keys for node operators

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1516]
**Is your feature request related to a problem? Please describe.**
currently, the framework generates keys on the agent level not on the service level.

This means that in order for the command;

autonomy deploy build to function, we need to provide a key path which users would need to edit manually.

```
autonomy deploy build ../../$KEY_PATH --password $PASSWORD --aev
```

**Describe the solution you'd like**

a bulk flag added to the sub command which allows service key generation and generates a file in the following format.

```
autonomy generate-key ethereum --service -n 1
```

required output

```
[
    {
        "address": "0xe969B67D80bb2b6E35be41b58A1B5c73e6d3259D",
        "private_key": "{\"address\": \"e96\", \"crypto\": {\"cipher\": \"aes-128-ctr\", \"cipherparams\": {\"iv\": \"7a\"}, \"ciphertext\": \"\", \"kdf\": \"scrypt\", \"kdfparams\": {\"dklen\": 32, \"n\": 262144, \"r\": 1, \"p\": 8, \"salt\": \"\"}, \"mac\": \"\"}, \"id\": \"\", \"version\": 3}"
    }
]
```

**Describe alternatives you've considered**

previously we have used a script to generate these key files;

```
"""Script to generate bulk ethereum keys for use with the 'aea build_deployment' subcommand."""
import json
from pathlib import Path
import sys        

import click
from aea.cli.utils.click_utils import password_option
from aea.crypto.registries import make_crypto


@click.command()
@click.option("-n", "--number-of-keys", "--number_of_keys", type=int, default=4)
@click.option(
    "-o", "--output-file", "--output_file", type=str, default="generated_keys.json"
)
@password_option(confirmation_prompt=True, required=True)
def generate_keys(number_of_keys: int, output_file: str, password: str) -> None:
    """Generates n number of keys to be used by deployment generator."""
    keys = []
    if Path(output_file).exists():
        print(f"Key file {output_file} already exists. Aborting.")
        sys.exit(0)
    for x in range(number_of_keys):
        account = make_crypto("ethereum")
        keys.append(
            {"address": account.address, "private_key": account.encrypt(password)}
        )
        print(f"Processed key generation {x}")
    with open(output_file, "w", encoding="utf8") as f:
        json.dump(keys, f, indent=4)


if __name__ == "__main__":
    generate_keys()  # pylint: disable=no-value-for-parameter


```

**Comment by angrybayblade** [comment]
This is not ideal since the `keys.json` file is supposed to contain keys which 

1. Has funds on the particular chain you're using for deployments
2. Needs to be registered as agent instances on the on-chain service registry 

And for the local deployments they're supposed be funded on the local hardhat deployment

**Comment by 8ball030** [comment]
OK, post a call with @DavidMinarsch where we deployed el collectoorr, we came to the conclusion that the current keys.json file should be changed so that there is not multiple ways of defining these key files.

Presently, we require all keys for an operator to be;

* either ALL encrypted or none encrypted
* in this very specific format. 

It would be great if we had a way of say, referencing multiple ethereum_private_key.txt files

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-aea/pull/461
