### ISSUE TITLE
Add generic selector group to kube deployment

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1585]
**Is your feature request related to a problem? Please describe.**
Implement a selector group on the template for the manifests that allows the selection of all of the agent instances.

**Describe the solution you'd like**
https://github.com/valory-xyz/open-autonomy/pull/1584
This pr proposes a small change to the template which enables this

**Describe alternatives you've considered**

**Additional context**

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1584
