### ISSUE TITLE
CLI tool for FSM spec check will pass when no files are found.

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1592]
suggested: raise `FileNotFoundError`

https://github.com/valory-xyz/open-autonomy/blob/1abe2adf56abde4a77a89df80cee48c8fe031d00/autonomy/cli/helpers/fsm_spec.py#L143-L170

**Comment by DavidMinarsch** [comment]
Don't see the benefit in raising here.

**Comment by Karrenbelt** [comment]
> Don't see the benefit in raising here.

could add a warning to inform there is no spec found in a particular module. Now however, if you specify an incorrect path, it will pass the check and you might think your specs are okay whereas they might not be.
