### ISSUE TITLE
`to_int` does not deal well with floats

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1614]
however it appears be used outside of tests so we might just want to remove it.

If not, then the following issues exist:
- it does not specify and delimit the precision of the floats it can operate on
- it does not specify a limit for the number of decimals.
- it does not deal with 'e' notation: e.g. 3.14159265359e-07

**Comment by Adamantios** [comment]
It is badly named. It is meant to parse a string and only keep its numbers. Moreover, it should have been moved to https://github.com/valory-xyz/apy-oracle when splitting the repos.
