### ISSUE TITLE
`TestTermination` not passing Tendermint health check

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1623]
This is a new issue but frequently recurring issue as of recently. Currently seen on PR #1620, #1621 and main: CI run [#6186](https://github.com/valory-xyz/open-autonomy/actions/runs/3630510890/jobs/6124133371).

In all cases this concerns `test_register_reset.TestTermination`

snippet: [failure.log](https://github.com/valory-xyz/open-autonomy/files/10170416/failure.log)

**Comment by DavidMinarsch** [comment]
No longer observed - closing for now (likely fixed with synchronized_data_class refactor between 0.6.0 and 0.7.0)
