### ISSUE TITLE
autonomy analyse handlers does not work properly

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1689]
### Subject of the issue

Upon executing
```autonomy analyse handlers -h http -i abstract_abci -i counter -i counter_client -i abstract_round_abci -i register_reset_abci -i register_reset_recovery_abci -i register_termination_abci -i registration_abci -i termination_abci -i test_abci -i reset_pause_abci```

(i.e., analyse http handler only for hello_world_abci), the following error message is displayed:

```Error: Handler file does not exist in /home/<user>/git/open-autonomy/packages/valory/skills/hello_world_abci```

However, the file `/home/<user>/git/open-autonomy/packages/valory/skills/hello_world_abci/handlers.py` does actually exist.

### Your environment
- OS: Ubuntu
- Python version: 3.10.9
- Package Version 0.6.0

### Steps to reproduce
See above.

### Expected behaviour
Command should work.

### Actual behaviour
Command does not work as expected. See above.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1752
