### ISSUE TITLE
autonomy deploy build --force not working properly when run in normal mode.

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1737]
### Subject of the issue
autonomy deploy build --force throws 

PermissionError: [Errno 13] Permission denied: 'node_key.json'

when run in normal (non-root) user mode. This is related to the fact that some files are created with special permissions (need to execute sudo rm --rf /abci_build to completely remove the deployment folder).

### Your environment
- OS: Ubuntu 22.04
- Python version: 3.10
- Package Version 0.7.0

### Steps to reproduce
Follow any of the guides and build a deployment in normal user mode.

### Expected behaviour
/abci_build should have same permissions as current user. It should not be required to be super user to delete the folder.

### Actual behaviour
See above.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1852
