### ISSUE TITLE
Provide framework support to initialize empty repository.

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1810]
**Is your feature request related to a problem? Please describe.**

The framework does not have a command line option to explicitly or implicitly initialize an empty local registry. 

1. In the absence of a `packages` directory:
    a. `autonomy init --[local | remote] --reset `: does not create a local registry not prints any error message.
    b. `autonomy --registry-path=./packages init --[local | remote] --reset`: complains about the directory not existing.
    When using `autonomy scaffold` produces an error:
    ```
    Error: Registry path not provided and local registry `packages` not found in current (.) and parent directory.
    ```

2. If the directory `./packages` exists, but not the `packages.json`:
    a. `autonomy init --[local | remote] --reset `: does not lauch error
    b. `autonomy --registry-path=./packages init --[local | remote] --reset`: does not launch error
    However, when using `autonomy scaffold` launches an (ugly) exception:
    ```
    (...)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/jose/git/wdir2/packages/packages.json'
    ```

**Describe the solution you'd like**

Some of the following should be considered:
1. Ensure a local registry is initialized appropriately after `autonomy init` or fail otherwise (correct folder and packages.json file).
2. Provide a command line to initialize an empty registry.
3. Initialize an empty registry implicitly when it is required (showing an approppriate warning or confirmation message to the user).

**Describe alternatives you've considered**
A partial doc (ugly) solution has been given in #PR1809

**Additional context**

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-aea/pull/590
