### ISSUE TITLE
This makes quite the assumtion that the only way to deploy from token id is into docker-compose

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1851]
https://github.com/valory-xyz/open-autonomy/blob/496d7185589845a2125bba39a708db6c20961cbe/autonomy/cli/helpers/deployment.py#L266

For now, i am hacking my way around this to use kube but this is none optiomal.

It would be great if either i could;

A) pass --kubernetes
B) pass --deploy False

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1853
