### ISSUE TITLE
Improve readability of error message for deploy from token-id

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1855]
**Is your feature request related to a problem? Please describe.**

When running deploy from token id, the error messages displayed to the user do not really tell the user what to do.

i.e. 

```
autonomy deploy from-token 1 ~/.keys/keys.json --use-ethereum
Building service deployment using token ID: 1
Error: RPC cannot be `None` for chain config; chain_type=ChainType.ETHEREUM
```

What do i need to do here?

**Describe the solution you'd like**
Id like to see the error output tell me that i need to set an environment variable. `ETHEREUM_CHAIN_RPC

I.e. 

```
Oh no! you have tried to run a command which expects the environment variable  ``ETHEREUM_CHAIN_RPC`
Please set this variable and try again
```

**Describe alternatives you've considered**

**Additional context**

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1920
