### ISSUE TITLE
Improve deploy-from token id eerror validations

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1856]
**Is your feature request related to a problem? Please describe.**
The default options for deploy from token-id fail requiring the usage of exotic flags and variables with no user feedbasck about this.

```
autonomy deploy from-token 1 keys.json --kubernetes
Building service deployment using token ID: 1
Fetching service metadata using chain type local
Error: Error connecting to the RPC
```
This should inform you that you need to set a variable at least, at best it shouldnt fail by default.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by angrybayblade** [comment]
The error log says that the local chain is being used

```
Fetching service metadata using chain type local
```

And you don't need to export env var for using a local chain.

If you're using other chains like goerli or mainnet it does mention that you need to export an environment variable

```
autonomy mint --use-goerli protocol packages/valory/protocols/acn/ --key ~/_key 
Error: RPC URL cannot be `None`, Please set the environment variable for goerli chain using `GOERLI_CHAIN_RPC` environment variable
```
and 

```
autonomy mint --use-ethereum protocol packages/valory/protocols/acn/ --key ~/_key 
Error: RPC URL cannot be `None`, Please set the environment variable for ethereum chain using `ETHEREUM_CHAIN_RPC` environment variable
```
