### ISSUE TITLE
Add flag to load env vars from file when building a deployment

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#1858]
We usually need to export env vars befores building an agent deployment. For the last months 90% of the problems I've faced while running agents had to do with problems in those vars: remember which ones to export, double checking their values are correct... Furthermore, when switching between services of different deployment types this can lead to frction in the development. Having a flag (domething like --env-file) that lets us specify a file where we store some vars would be easier.

**Comment by 8ball030** [comment]
I 100% agree with this.

Apply environment variables should be default.

this would save a load of time from my side as well, and you could create different env var files for different deployments.
