### ISSUE TITLE
Autonomy publish does not override remote registry usage when using the flag --registry-path

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1862]
### Subject of the issue

Inconsistency issue:

`autonomy --registry-path=../packages publish` does not override `autonomy init` initialized with a remote repository.

Explanation:

When initialized with `autonomy init --remote` and the user executes the following (or other) commands:
`autonomy --registry-path=../packages add skill <skill>`

the configuration is overriden and `<skill>` is added from the local registry.

However, when the user executes 
`autonomy --registry-path=../packages publish`
it does NOT override the usage of the remote registry. Instead, the user has to initialize the registre locally if he wishes to store a component in the local registry.

**Check if this also happens for `push`.**

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
See above.

### Expected behaviour
The flag `--registry-path=` should override the usage of the remote registry whenever it is invoked, for all the commands. Otherwise is very confusing.

### Actual behaviour
See above.

**Comment by jmoreira-valory** [comment]
UPDATE:
This seems to be solved by adding the flag `--local`

However, this raises the question: Why some commands require --registry-path  and --local, whereas other commands only require --registry-path to work?

**Comment by angrybayblade** [comment]
Closing since the issue was solved by using the `--local` flag, if you have suggestion regarding the registry selection UX please open a separate issue
