### ISSUE TITLE
Autonomy scaffold fsm -tlr does not update local registry packages.json file

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1864]
### Subject of the issue

When executing
`autonomy scaffold -tlr fsm your_fsm_app_name --spec fsm_specification.yaml`

it successfully creates an FSM app skill inside the folder
`./packages/your_name/skills/your_fsm_app_name`

**However, the file
`./packages/packages.json`
is not updated with the newly created skill.**

Even after calling
```
autonomy push skill ./packages/your_name/skills/your_fsm_app_name/
autonomy packages sync
```
the local `packages.json` file is not updated either.

Also, the downloaded packages are listed under `dev`, when it should be under `third_party`
```
{
    "dev": {
        "protocol/valory/contract_api/1.0.0": "bafybeidv6wxpjyb2sdyibnmmum45et4zcla6tl63bnol6ztyoqvpl4spmy",
        "contract/valory/service_registry/0.1.0": "bafybeid4wyte27tanmeiyzkjfvtvf5yyjngdsvsqvve5bzxwtzjoioubgi",
        "protocol/valory/abci/0.1.0": "bafybeig3dj5jhsowlvg3t73kgobf6xn4nka7rkttakdb2gwsg5bp7rt7q4",
        "connection/valory/abci/0.1.0": "bafybeiedhipcrpx7sg7qwitwox6iqrbbb4vfnvqqyok2vc6wq6inrcszey",
        "skill/valory/abstract_abci/0.1.0": "bafybeihkrunmigvlcze7uxhafj2h3kvpf2kifggq7zqj42n2we4mcwuvou",
        "protocol/valory/http/1.0.0": "bafybeifyoio7nlh5zzyn5yz7krkou56l22to3cwg7gw5v5o3vxwklibhty",
        "connection/valory/http_client/0.23.0": "bafybeidykl4elwbcjkqn32wt5h4h7tlpeqovrcq3c5bcplt6nhpznhgczi",
        "protocol/valory/ledger_api/1.0.0": "bafybeih6hfzj2obw5oajnt6ng6355edgvi5ngoaub44vpuszqoplfvyaom",
        "connection/valory/ledger/0.19.0": "bafybeicxcypcg2lxmtktbmuhqcyluzmasfsdeljyk2pvaabzc3h2jmcsui",
        "protocol/valory/acn/1.1.0": "bafybeignmc5uh3vgpuckljcj2tgg7hdqyytkm6m5b6v6mxtazdcvubibva",
        "connection/valory/p2p_libp2p_client/0.1.0": "bafybeidwcobzb7ut3efegoedad7jfckvt2n6prcmd4g7xnkm6hp6aafrva",
        "protocol/valory/tendermint/0.1.0": "bafybeicusvezoqlmyt6iqomcbwaz3xkhk2qf3d56q5zprmj3xdxfy64k54",
        "protocol/valory/ipfs/0.1.0": "bafybeihlgai5pbmkb6mjhvgy4gkql5uvpwvxbpdowczgz4ovxat6vajrq4",
        "connection/valory/ipfs/0.1.0": "bafybeia7kzgw4tmkl6k2vjbnss4egvhcf4fmt7cnmpjjjbjogz2bu2j3fu",
        "protocol/open_aea/signing/1.0.0": "bafybeibqlfmikg5hk4phzak6gqzhpkt6akckx7xppbp53mvwt6r73h7tk4",
        "skill/valory/abstract_round_abci/0.1.0": "bafybeib2jw7hjccou42wis35orckwycb2dgjk7yw46anuqysf2h7su3fi4"
    },
    "third_party": {}
}
```

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Prepare a workspace folder containing a `./packages` local repository.
Execute the command within the workspace folder.

### Expected behaviour
The file
`./packages/packages.json`
should contain a proper entry for 
`skill/your_name/your_fsm_app_name/0.1.0`

### Actual behaviour
See above.

I could not easily find a way so that the packages.json file is automatically populated, besides manually editing the file.

**Comment by angrybayblade** [comment]
Addressed here https://github.com/valory-xyz/open-autonomy/pull/1876

**Comment by jmoreira-valory** [comment]
Ok I see this is also issue https://github.com/valory-xyz/open-autonomy/issues/1894
addressed in https://github.com/valory-xyz/open-autonomy/pull/1943

I'm closing this.
