### ISSUE TITLE
feature request / bug report: autonomy packages init

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1866]
**Is your feature request related to a problem? Please describe.**
When creating a fresh project, there is no facility for an autonomy packages init which would create local packages and packages/packages.json

This means that you have to look into other repos to find a reference before you can run autonomy commands

**Describe the solution you'd like**
autonomy packages init 
creates the local packages directory and an empty packages.json if it doesnt exist

**Describe alternatives you've considered**

**Additional context**

**Comment by jmoreira-valory** [comment]
This issue is related to https://github.com/valory-xyz/open-autonomy/issues/1810

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-aea/pull/590
