### ISSUE TITLE
Feature request: No clean up post scaffold failure.

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1867]
### Subject of the issue

There is no clean up when scaffolding a fsm which fails validation

i.e.
when running;

```
autonomy scaffold -tlr fsm --spec fsm_spec.yaml eightballer
```
I get the following error as I have poorly defined my fsm;
```
autonomy.analyse.abci.app_spec.DFASpecificationError: DFA spec has the following issues:
 - Transitions out from final states: {'ObjectiveComplete'}
 ```
 
 I would expect that if the command fails, it does not create artefacts, or cleans them up post failure.
 
 Presently, the application will leave artefacts on the users working directory which must be cleaned, if we validate the spec prior to creating the artefacts, the users wont have to clean their working directory

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by dvilelaf** [comment]
Yes, 100% agree.
