### ISSUE TITLE
Name Clashes when generating scaffolded fsm spec.

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1869]
### Subject of the issue
When scaffolding there appears to be namespace clashes leading to failing tests.

This can be replicated using a simple fsm spec and looking at the generated behaviours, where the clashes are seen with the base behaviour and the `abci_app_cls ` attribute of the final Abci app in behaviour.py

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by dvilelaf** [comment]
Both Jose and me found this last week as well. I opened a ticket on [Trello](https://trello.com/c/mQUnqqOr/1974-fix-2-scaffolding-issues).

**Comment by angrybayblade** [comment]
Addressed in - https://github.com/valory-xyz/open-autonomy/pull/1881

I've tried scaffolding a skill package using [fsm_specification.yaml](https://github.com/valory-xyz/trader/blob/main/packages/valory/skills/trader_abci/fsm_specification.yaml), the issue re the base behaviour and abci_app_cls name clashes does not appear to be there anymore.

```python
(...)

class TraderBaseBehaviour(BaseBehaviour, ABC):
    """Base behaviour for the hello skill."""

(...)

class TraderRoundBehaviour(AbstractRoundBehaviour):
    """TraderRoundBehaviour"""

    initial_behaviour_cls = RegistrationStartupBehaviour
    abci_app_cls = TraderAbciApp  # type: ignore
    behaviours: Set[Type[BaseBehaviour]] = [
 
(...)
```

**Comment by angrybayblade** [comment]
Addressed in - https://github.com/valory-xyz/open-autonomy/pull/1881

I've tried scaffolding a skill package using [fsm_specification.yaml](https://github.com/valory-xyz/trader/blob/main/packages/valory/skills/trader_abci/fsm_specification.yaml), the issue re the base behaviour and abci_app_cls name clashes does not appear to be there anymore.

```python
(...)

class TraderBaseBehaviour(BaseBehaviour, ABC):
    """Base behaviour for the hello skill."""

(...)

class TraderRoundBehaviour(AbstractRoundBehaviour):
    """TraderRoundBehaviour"""

    initial_behaviour_cls = RegistrationStartupBehaviour
    abci_app_cls = TraderAbciApp  # type: ignore
    behaviours: Set[Type[BaseBehaviour]] = [
 
(...)
```
