### ISSUE TITLE
`autonomy fetch --alias` should succeed if there is no folder with the same name as the alias

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1886]
### Subject of the issue

When using `autonomy fetch --alias` it fails if there exists a folder with the default name of the agent (regardles whether I specify another alias). For example:

```
autonomy fetch valory/hello_world:0.1.0:bafybeic3czcb7fpzru3fl4noxdwgwyzirqk6cqh763h6aio7ugl6qm5gha
autonomy fetch valory/hello_world:0.1.0:bafybeic3czcb7fpzru3fl4noxdwgwyzirqk6cqh763h6aio7ugl6qm5gha --alias hello_world_agent
```

Will complain that `hello_world` folder already exists. But this is not the folder I specified (it is `hello_world_agent`).

on the other hand,

```
autonomy fetch valory/hello_world:0.1.0:bafybeic3czcb7fpzru3fl4noxdwgwyzirqk6cqh763h6aio7ugl6qm5gha --alias hello_world_agent
autonomy fetch valory/hello_world:0.1.0:bafybeic3czcb7fpzru3fl4noxdwgwyzirqk6cqh763h6aio7ugl6qm5gha
```

will succeed.

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
The command should not fail if I specify an alias which does not match an existing folder.

### Actual behaviour
See above.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1947
