### ISSUE TITLE
`autonomy fetch --alias` ignored when fetching a `--service`

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1887]
### Subject of the issue

`autonomy fetch bafybeiangkjd6y5jjpubeog25lggrmq3y64b2cqurhmxs26i4tddksbhiq --alias hello_world_service --service
`
fetches the service to the `hello_world` (default name) folder.

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
It should create the folder `hello_world_service`.

### Actual behaviour
See above.

**Comment by angrybayblade** [comment]
https://github.com/valory-xyz/open-autonomy/pull/1947
