### ISSUE TITLE
Port binding does not work as intended

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#1899]
The port binding works the opposite way than described on https://github.com/valory-xyz/open-autonomy/pull/1882#discussion_r1138620628. In essence:

- this works:

```
deployment:
  agent:
    ports:
      0:
        8000: ${AGENT0_PORT:int:8000}
      1:
        8001: ${AGENT1_PORT:int:8000}
      2:
        8002: ${AGENT2_PORT:int:8000}
      3:
        8003: ${AGENT3_PORT:int:8000}
```

- this does not work:

```
deployment:
  agent:
    ports:
      0:
        8000: ${AGENT0_PORT:int:8000}
      1:
        8000: ${AGENT1_PORT:int:8001}
      2:
        8000: ${AGENT2_PORT:int:8002}
      3:
        8000: ${AGENT3_PORT:int:8003}
```

This is not problematic, but it means that:
1. We cannot specify overrides for the exposed ports.
2. We need to update [the documentation for that](https://docs.autonolas.network/open-autonomy/configure_service/service_configuration_file/?h=external#configure-external-ports).

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1944
