### ISSUE TITLE
Mint private components not possible with the CLI.

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1938]
**Is your feature request related to a problem? Please describe.**
The current implementation of `autonomy mint` requires that the minted component, and its dependencies be published on the IPFS. This is enforced so that the command can perform the required dependency checks, which is a nice feature.

However, it could be the case that some author wants to register a component in the Autonolas Protocol without making it public on the remote IPFS registry. This case cannot be addressed by the current implementation of `autonomy mint`.

**Describe the solution you'd like**
Clarify if this issue will be considered or not (probably it is not worth the effort).

**Describe alternatives you've considered**
Package authors could use the Autonolas Protocol web app to mint components in this case, because the web app does not do any dependency check.

**Comment by angrybayblade** [comment]
This is not an issue of the `autonomy mint` command group, this is by design of the Autonolas protocol that a component needs to be present on the IPFS registry.

**Comment by jmoreira-valory** [comment]
I am unsure about this. In principle you can specify "anything" for the hash on the Autonolas protocol registry, it does not chech (it can't check) that it's actually published on the IPFS or not.
