### ISSUE TITLE
`analyse service` mistakenly checks non-abci skills

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-autonomy#1988]
**Is your feature request related to a problem? Please describe.**
`analyse service` mistakenly treats non-abci skills like abci skills

**Describe the solution you'd like**
The tool should automatically detect if a skill is an abci skill and only apply the checks on those

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/1982
