### ISSUE TITLE
Service overriding mechanism and service analyzer conflicting

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#2013]
https://github.com/valory-xyz/trader/pull/19#issue-1811696690

**Comment by Adamantios** [comment]
Another issue with the service analyzer was detected on https://github.com/valory-xyz/trader/pull/29.
I should have detected 1 and 2.

**Comment by angrybayblade** [comment]
Re https://github.com/valory-xyz/trader/pull/19#issue-1811696690 I don't see how this is issue, if an override is defined at the agent level the service needs to have override defined for that component or defined the override at the agent level does not make any sense

**Comment by Adamantios** [comment]
> Re https://github.com/valory-xyz/trader/pull/19#issue-1811696690 I don't see how this is issue

The first line of the PR description gives the answer:

> Remove the abci connection's override from the service file because it was not allowing any other connection's override to work properly.

Overriding this to satisfy the service analyzer does not allow any other connection override to work properly.

**Comment by angrybayblade** [comment]
Fixed https://github.com/valory-xyz/open-autonomy/pull/2093
