### ISSUE TITLE
Dry run support for the minting tools

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#2022]
Incorporating the ability to perform a dry run with the minting tools would be really useful for testing purposes.

This could be done by using a fork for example.

**Comment by DavidMinarsch** [comment]
I agree that some form of dry run and stepped approach is key here. I propose as a first step to enable the flag "--dry-run" that does everything except send the final transaction. The metadata is printed so one can see what the tool is about to commit to.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/2116
