### ISSUE TITLE
[request] Please change order of install and build

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#2080]
https://github.com/valory-xyz/open-autonomy/blob/aec2f4ae5ae3577b91c546ba54ab2d4f2905d357/deployments/Dockerfiles/autonomy/scripts/install.sh#L16

Please swap this such that the build occurs prior to the install.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/2081
