### ISSUE TITLE
Safe nonce reuse handling

### ISSUE THREAD

**Issue by 0xArdi** [valory-xyz/open-autonomy#2105]
Due to various reasons (ex. bad RPC read) a service might end up reading an old safe nonce when sending a transactions through the transaction settlement abci.
Whenever this is the case, the following things happen:
1. `ValidateTransactionRound` ends with Event.NEGATIVE, which leads to `CheckTransactionHistoryRound` [(check here)](https://github.com/valory-xyz/open-autonomy/blob/v0.13.3/packages/valory/skills/transaction_settlement_abci/rounds.py#L748)
2. Whenever this happens, the `CheckTransactionHistoryRound` goes through all the txs in the history, checking for reasons why they might've failed, including the [safe_nonce_reuse](https://github.com/valory-xyz/open-autonomy/blob/v0.13.3/packages/valory/skills/transaction_settlement_abci/behaviours.py#L618).
When that is the case, this round assumes that at least one valid transaction has been sent. Which doesn't have to be the case. If not a single tx has gone through, we transition to `SelectKeeperTransactionSubmissionBRound` [(check here)](https://github.com/valory-xyz/open-autonomy/blob/2c7e453cb28d8ece8b59752353fe0b6eb2998d1e/packages/valory/skills/transaction_settlement_abci/rounds.py#L757C29-L757C68)
3. `SelectKeeperTransactionSubmissionBRound` just keeps trying to send the transaction again with the same safe nonce. 
4. We get stuck in this loop.

To avoid getting stuck in this loop, I would suggest we have a special case to handle the situation when verification fails and the safe nonce has been reused on `CheckTransactionHistoryRound`, and transition to a FAILED_ROUND, and let the sending abci_app handle it. 

Note that the safe nonce is getting set in [get_raw_safe_transaction_hash](https://github.com/valory-xyz/open-autonomy/blob/v0.13.3/packages/valory/contracts/gnosis_safe/contract.py#L334). 
Alternatively, we could look into making this call in the transaction settlement abci.

**Comment by Adamantios** [comment]
> To avoid getting stuck in this loop, I would suggest we have a special case to handle the situation when verification fails and the safe nonce has been reused on CheckTransactionHistoryRound

What would that special case be? 
Also, if the RPC is still misbehaving when reaching this check round, we cannot know if the utilized safe nonce was incorrect.

**Comment by 0xArdi** [comment]
I would say we set a var `safe_nonce_reused = True`, whenever we get [here](https://github.com/valory-xyz/open-autonomy/blob/v0.13.3/packages/valory/skills/transaction_settlement_abci/behaviours.py#L614), and return with a new status [here](https://github.com/valory-xyz/open-autonomy/blob/v0.13.3/packages/valory/skills/transaction_settlement_abci/behaviours.py#L631). Otherwise we will infinitely try to send a bad tx. This is of course only for cases when we can verify that this is the case.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-autonomy/pull/2106
