### ISSUE TITLE
Core ledger interactions should utilize the default chain id

### ISSUE THREAD

**Issue by 0xArdi** [valory-xyz/open-autonomy#2123]
As of `open-autonomy@0.13.7` the `default_chain_id` is not being used in `termination_abci`. 
It's possible there are other such occurrences.

**Comment by Devanshusisodiya** [comment]
@0xArdi Is this issue resolved? Because I can see [default chain id](https://github.com/valory-xyz/open-autonomy/blob/9ef15f16398442fbbb4bec8b15c2d18365842e22/packages/valory/skills/termination_abci/behaviours.py#L196) being used here.

**Comment by 0xArdi** [comment]
@Devanshusisodiya looks like it was added to termination. We need to check if all such occurrences have been addressed.

**Comment by Devanshusisodiya** [comment]
@0xArdi are all functions using `get_contract_api_response` performing core ledger interactions? In that case `default_chain_id` should be used as a parameter in all of them according to the issue definition right?
