### ISSUE TITLE
Update incorrect docstring

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#2135]
Incorrect docstring:

https://github.com/valory-xyz/open-autonomy/blob/v0.13.9.post1/packages/valory/skills/abstract_round_abci/common.py#L56C1-L57

**Comment by Devanshusisodiya** [comment]
@Adamantios I see that `RandomnessBehaviour` class is being referenced in a lot of places for example the following files

- `docs/api/skills/abstract_round_abci/common.md`

and so on. So such files should also be updated with the changes of docstring if being mentioned?

**Comment by Adamantios** [comment]
> @Adamantios I see that `RandomnessBehaviour` class is being referenced in a lot of places for example the following files
> 
> * `docs/api/skills/abstract_round_abci/common.md`
> 
> and so on. So such files should also be updated with the changes of docstring if being mentioned?

Yes, but running `tox -e generate-api-documentation` would take care of that, as the docs are auto-generated.

**Comment by Devanshusisodiya** [comment]
@Adamantios Ive raised a [pull request](https://github.com/valory-xyz/open-autonomy/pull/2162) for this issue, please review and provide your comments.
