### ISSUE TITLE
Missing dependency undetected

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#2218]
A dependency missing from the agent's configuration went undetected by our framework's checks. 
This dependency was present in a custom package. More info in https://github.com/valory-xyz/baby-degen/pull/68.

**Comment by angrybayblade** [comment]
You need to define the custom package as dependency for the agent, this way the `aea install` will take care of installing the package dependencies.

```yaml
customs:
- valory/trend_following_strategy:0.1.0:...
```
