### ISSUE TITLE
Implement a generic swap behaviour inside liquidity provision skill

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#397]
**Is your feature request related to a problem? Please describe.**
At the moment, the LP skill implements the token swapping as part of a bigger multisend transaction that includes approving, swapping and entering/exiting pools. We should have approving+swapping separated and implemented in a generic way so it is reusable. I've thought of two possible solutions:

- We work at pair level so the swap takes us from holding A + B to any other token pair C + D. 
- We work at token level so we swap A to any other token B individually. We would need to call this behaviour 2 times in this case.

**Describe the solution you'd like**
Implement a generic swap behaviour inside liquidity provision skill

**Comment by Adamantios** [comment]
Moved to the new repo: https://github.com/valory-xyz/liquidity-rebalancing/issues/4
