### ISSUE TITLE
Wrong arguments in message

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-autonomy#494]
**Is your feature request related to a problem? Please describe.**
The tx data here (https://github.com/valory-xyz/consensus-algorithms/blob/main/packages/valory/skills/transaction_settlement_abci/behaviours.py#L288) is of type AttributeDict which is not a primitive type and therefore raises an exception when passed as an argument.

<img width="908" alt="Screenshot 2022-02-05 at 20 20 56" src="https://user-images.githubusercontent.com/19314578/152660477-d07e3a63-3e0a-470e-8efd-032457b6980c.png">

**Describe the solution you'd like**
Fix

**Comment by 0xArdi** [comment]
#495 claims to fix this
