### ISSUE TITLE
Warning: CryptographyDeprecationWarning: Blowfish has been deprecated

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#761]
### Subject of the issue
When starting the oracle the following message appears:
`CryptographyDeprecationWarning: Blowfish has been deprecated`
It seems to have to do with [this](https://github.com/paramiko/paramiko/issues/2038).

### Your environment
- OS: elementary OS 5.1 (Ubuntu 20.04)
- Python version: 3.8.10

### Steps to reproduce
Just run the oracle

### Expected behaviour
Message should not appear

### Actual behaviour
Message appears

**Comment by angrybayblade** [comment]
This was fixed in paramiko 2.11.0, currently we're using paramiko 3.3.1
