### ISSUE TITLE
rename --docker flag to --docker-compose

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#819]
not sure if --use-hardhat is the correct terminology, as the network is defined at a service level, 
rather deploy hardhat might be more appropriate?

Also, what are your thoughts on changing the flag --docker to --docker-compose. We can then use that deployment type env var within this makefile, as the flag, maybe reduce the size of this make file a bit?

_Originally posted by @8ball030 in https://github.com/valory-xyz/consensus-algorithms/pull/809#discussion_r876887490_

**Comment by DavidMinarsch** [comment]
Done a while ago
