### ISSUE TITLE
Properly fix block height between resets

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#879]
**Is your feature request related to a problem? Please describe.**
Block height between resets might be incorrect in edge cases.

**Describe the solution you'd like**
Properly fix block height between resets, instead of hacking around it by using an offset, as proposed in https://github.com/valory-xyz/consensus-algorithms/pull/871#issuecomment-1143997916.

**Describe alternatives you've considered**
https://github.com/valory-xyz/consensus-algorithms/pull/871#issuecomment-1143997916

**Additional context**
Currently, the issue is addressed in a hacky way, by adding a height offset in #878 .

**Comment by DavidMinarsch** [comment]
Recent refactors in preparation for 0.9.0 cover this
