### ISSUE TITLE
Generalise deploy tests & more generally for tests

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#880]
I think we need to generalise these tests because this file is getting bigger and bigger just by introduction of a small feature

_Originally posted by @angrybayblade in https://github.com/valory-xyz/consensus-algorithms/pull/870#discussion_r888071486_

**Comment by angrybayblade** [comment]
Addressed here https://github.com/valory-xyz/open-autonomy/pull/1549
