### ISSUE TITLE
Move deployment and tools from Makefile to autonomy CLI

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#951]
**Is your feature request related to a problem? Please describe.**
[See this](https://github.com/valory-xyz/open-autonomy/pull/950#discussion_r897131392). Several command tools like `make build-deploy` or `make run-oracle-dev` live inside the Makefile instead of the autonomy CLI. This forces a framework user to download our repo to have it. The CLI should be enough for the users to have all the required functionality, and the Makefile should only contain functionality related to the framework development.

**Describe the solution you'd like**
- Implement those make commands as CLI tools.
- Update the docs to match the new commands

**Comment by DavidMinarsch** [comment]
Mostly addressed by now
