### ISSUE TITLE
Observation interval should not be too small

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#956]
### Subject of the issue
The developer may choose a tiny amount for the observation interval, which is going to break the reset with Tendermint. We should probably restrict the user from inserting a small amount for the observation interval.

Please also take a look at the description in #955 .

### Expected behaviour
The developer should be restricted from choosing a tiny observation interval, since it is practically impossible to synchronize the majority of the agents so fast to perform a Tendermint reset properly.

### Actual behaviour
The developer currenlty may choose any value it wants for the observation interval.

**Comment by DavidMinarsch** [comment]
This is a more general issue which should apply for all Rounds
