### ISSUE TITLE
Terminate all agents simultaneously at e2e tests

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#962]
### Subject of the issue
The agents are terminating independently from each other in the e2e tests. This might cause issues when the test depends on Tendermint since the majority of the nodes might not be feasible for the rest of the agents to end their rounds successfully.

### Steps to reproduce
Run any e2e test and observe the logs for the terminating message:
```
AEA 'agent_name' interrupted!
```

### Expected behaviour
The agents should terminate simultaneously.

### Actual behaviour
The agents terminate immediately after they succeed, independently.

**Comment by Karrenbelt** [comment]
@Adamantios Is this still an issue?

**Comment by Adamantios** [comment]
No, this is not yet an issue. Closing this.
